jadwal/urls.py
from django.urls import path
from . import views
app_name="jadwal"
urlpatterns = [
    path('', views.isi_Jadwal, name="jadwal_form"),
    path('terima', views.buat_Jadwal, name="terima"),
    path('delete/<id>', views.hapus_Jadwal, name="hapus"),
]

portofolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='beranda'),
    path('riwayat/', views.riwayat, name='riwayat'),
    path('fakta/', views.fakta, name='fakta'),
    path('portofolio/', views.porto, name='porto'),
    path('motivasi/', views.motivasi, name='motivasi')
]

story4_project/urls.py
from django.contrib import admin
from django.urls import path, include
from portofolio.views import *
from jadwal.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portofolio.urls')),
    path('jadwal/', include('jadwal.urls'))
]

jadwal/models.py
from django.db import models

class Jadwal_Kegiatan(models.Model):
    kategori = models.CharField(max_length = 100)
    nama_kegiatan = models.CharField(max_length = 100)
    tanggal_kegiatan = models.DateField(auto_now_add=False, default=None, null=True)
    waktu_kegiatan = models.TimeField(auto_now_add=False, null=True)
    tempat = models.CharField(max_length = 100)

portofolio/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms
from . import models

class InputDate(forms.DateInput):
    input_type = 'date'

class InputTime(forms.TimeInput):
    input_type = 'time'

class BuatJadwal(forms.ModelForm):
    class Meta:
        model = models.Jadwal_Kegiatan
        fields = ['kategori', 'nama_kegiatan', 'tanggal_kegiatan', 'waktu_kegiatan', 'tempat']
        widgets = {
            'tanggal_kegiatan' : InputDate,
            'waktu_kegiatan' : InputTime
        }

jadwal/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Jadwal_Kegiatan

def buat_Jadwal(request):
    if request.method == 'POST':
        form = forms.BuatJadwal(request.POST)
        if form.is_valid:
            form.save()
            return redirect ('jadwal:jadwal_form')
    else:
        form = forms.BuatJadwal()
        return render(request, 'buat_jadwal.html', {'form_jadwal':form})

def isi_Jadwal(request):
    if request.method=='POST':
        form = forms.BuatJadwal(request.POST)
        if form.is_valid:
            form.save()
        
    semua_jadwal = Jadwal_Kegiatan.objects.all().order_by('tanggal_kegiatan','waktu_kegiatan')
    return render(request, "hasil_form.html", {'semua_jadwal':semua_jadwal})

def hapus_Jadwal(request, id):
    jadwal_hapus = Jadwal_Kegiatan.objects.get(id=id)
    jadwal_hapus.delete()
    return redirect('jadwal:jadwal_form')

portofolio/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "portofolio/beranda.html")

def fakta(request):
    return render(request, "portofolio/fakta.html")

def riwayat(request):
    return render(request, "portofolio/riwayat.html")

def porto(request):
    return render(request, "portofolio/portofolio.html")

def motivasi(request):
    return render(request, "portofolio/motivasi.html")

jadwal/templates/buat_jadwal.html
{% extends "portofolio/template.html" %}
{% load static %}
{% block title %} Jadwal {% endblock %}
{% block content %}
    <form class="site-form" action="/jadwal/terima" method="POST">
        {% csrf_token %}
        <p>Kategori: {{ form_jadwal.kategori }} </p>
        <p>Nama Kegiatan: {{ form_jadwal.nama_kegiatan }}</p>
        <p>Tanggal Kegiatan: {{ form_jadwal.tanggal_kegiatan }}</p>
        <p>Waktu Kegiatan: {{ form_jadwal.waktu_kegiatan }}</p>
        <p>Tempat: {{ form_jadwal.tempat }}</p>
        <button type="submit" class="btn btn-light" id="btn-tambahjadwal">Tambah Jadwal</button>
    </form>
{% endblock content %}

jadwal/templates/hasil_form.html
{% extends "portofolio/template.html" %}
{% load static %}
{% block title %} Hasil Jadwal {% endblock %}
{% block content %}

    {% if semua_jadwal %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Kategori</th>
                    <th scope="col">Nama Kegiatan</th>
                    <th scope="col">Tanggal Kegiatan</th>
                    <th scope="col">Waktu Kegiatan</th>
                    <th scope="col">Tempat</th>
                    <th scope="col">Hapus Jadwal</th>
                </tr>
            </thead>
            {% for object_isian in semua_jadwal %}
            <tr>
                <td>{{ object_isian.kategori }}</td>
                <td>{{ object_isian.nama_kegiatan }}</td>
                <td>{{ object_isian.tanggal_kegiatan }}</td>
                <td>{{ object_isian.waktu_kegiatan }}</td>
                <td>{{ object_isian.tempat }}</td>
                <td><a href= "{% url 'jadwal:hapus' id=object_isian.id %} "> <button type="submit">Hapus</button> </a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
        <h1>Belum ada jadwal</h1>
    {% endif %}
    <a href="{% url 'jadwal:terima' %}"><button type="button" class="btn btn-light" id="btn-buatjadwal">Buat Jadwal Baru</button></a>

{% endblock content %}

portofolio/templates/portofolio/beranda.html
{% extends "portofolio/template.html" %}
{% load static %}
{% block title %} Beranda {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-3 biodata">
                <img src="{% static 'images/Evando.jpg' %}" class="img-fluid" id="profile-photo">
                <p>Evando Wihalim</p>
                <p>Fakultas Ilmu Komputer</p>
                <p>Universitas Indonesia</p>
                <p>2018</p>
            </div>
            <div class="col short-story">
                <h3>Tentang saya</h3>
                <p>Hi, saya Evando.</p><br>
                <p>Programmer. Fotografer. Video Editor Amatir.</p><br>
                <p>Berdomisili di Depok, bertempat tinggal di Bekasi. Seorang mahasiswa Fakultas Ilmu Komputer Universitas Indonesia.</p><br>
                <p>Tertarik dengan dunia pemrograman web, fotografi, editing video, kuliner, musik, dan buku.</p><br>
                <p>Suka dengan suasana kerja yang bersahabat dan mendukung produktivitas. 
                    Lebih suka untuk membuat perencanaan dalam melakukan suatu hal namun tetap dapat 
                    sigap dalam melakukan hal yang mendadak</p>
                <p>Cenderung mudah beradaptasi dan mudah untuk bersosialisasi.</p><br>
                <p>Saya adalah seseorang yang tekun,
                        mengerjakan tugas secepat mungkin
                        setelah diberikan, teliti, mampu memimpin
                        dan bekerja sama. Saya juga dapat mencari
                        solusi atas masalah secara kreatif. Saya
                        juga merupakan orang yang mengerjakan
                        sesuatu semaksimal mungkin.</p>
            </div>
        </div>
    </div>
{% endblock content %}

portofolio/templates/portofolio/fakta.html
{% extends "portofolio/template.html" %}
{% block title %} Fakta Unik {% endblock %}
{% block content %}
    <div class="container-fakta">
        <h4>4 Fakta Menarik Tentang Bahasa Pemrograman Python</h4>
        <div class="container-fakta-item">
            <p class="judul-fakta">Mengapa dikenal sebagai ‘Python’</p><hr>
            <p>Menurut pencipta Guido Van Rossum, nama bahasa ini berasal dari seri komedi Inggris “Monty Python Flying Circus”. 
                Komedi itu ditayangkan di BBC pada tahun 1970-an dan memberi sang pencipta semacam hiburan selama perkembangan bahasa. 
                Juga, Van Rossum menginginkan nama yang pendek, dan misterius. Sesuatu yang akan menarik perhatian semua orang.
            </p>
        </div>
    
        <div class="container-fakta-item fakta-even">
            <p class="judul-fakta">Python telah menyusul Prancis di sekolah dasar</p><hr>
            <p>Pada tahun 2015, Python menyalip bahasa Prancis menjadi bahasa terpopuler yang diajarkan di sekolah dasar. 
                Statistik mengungkapkan bahwa 6 dari 10 orang tua lebih suka anak-anak mereka belajar Python daripada Perancis.
                Ini hanya menunjukkan bahwa banyak orang menghargai pentingnya pemrograman Python.
                Hal yang sama berlaku untuk anak-anak. 
                Statistik yang sama mengungkapkan bahwa 75% anak sekolah dasar lebih suka belajar bagaimana mengendalikan robot daripada belajar bahasa Prancis
            </p>
        </div>

        <div class="container-fakta-item">
            <p class="judul-fakta">Python memiliki varian C dan Java</p><hr>
            <p>Meskipun merupakan bahasa pemrograman independen, Python memiliki varian untuk bahasa pemrograman C dan Java. 
                Varian C dikenal sebagai CPython dan dirancang untuk memberikan Python keuntungan dari C. 
                Salah satu karakteristik ini adalah dalam hal kinerja. Varian dapat bertindak baik sebagai penerjemah dan sekaligus sebagai kompiler.
                Varian Java dari Python dikenal sebagai Jython. Jython membawa beberapa aspek kunci Java seperti produktivitas dan memungkinkan mereka untuk berjalan di mesin virtual.
            </p>
        </div>
    
        <div class="container-fakta-item fakta-even">
            <p class="judul-fakta">Python adalah bahasa open source</p><hr>
            <p>Python tidak memiliki lisensi kepemilikan, sehingga siapapun diizinkan untuk memberikan kontribusi mereka
                dalam pengembangan bahasa Python.
            </p>
        </div>
        <a href="https://teknologi.id/insight/10-fakta-menarik-tentang-bahasa-pemrograman-python-bag-1/">Sumber: Teknologi.id (klik untuk menuju ke laman sumber)</a>
    </div>
{% endblock content %}

portofolio/templates/portofolio/motivasi.html
{% extends "portofolio/template.html" %}
{% block title %} Motivasi {% endblock %}
{% block content %}
    <div class="container-fakta">
        <h4>Kutipan Motivasi Hidup</h4>
        <div class="container-fakta-item">
            <p class="judul-fakta">Kerjakan dengan Lebih dan Sepenuh Hati</p><hr>
            <p>“Ia yang mengerjakan lebih dari apa yang dibayar pada suatu saat akan dibayar lebih dari apa yang ia kerjakan” - Napoleon Hill <br>
                <i>“The man who does more than he is paid for will soon be paid more than he does”</i> -  Napoleon Hill<br><br>
                Tip: Selalu ikhlas bekerja daripada apa yang dibayarkan kepada Anda saat ini, 
                maka Anda akan meraih sebuah hasil yang berlipat ganda pada masa mendatang. 
                Buat komitmen mulai hari ini untuk selalu memberikan yang terbaik, 
                apa pun yang Anda kerjakan setiap hari.
            </p>
        </div>
    
        <div class="container-fakta-item fakta-even">
            <p class="judul-fakta">Syukuri dan Hargai Hal-Hal  yang Anda Miliki</p><hr>
            <p>“Janganlah menganggap remeh hal-hal yang terdekat dengan hati Anda. 
                Rangkullah mereka seperti sama berharganya dengan hidup Anda, 
                karena tanpa mereka hidup adalah sia-sia” - Peribahasa Cina <br>

                <i>“Do not take for granted the things closest to your heart. 
                    Cling to them as you would with your life, for without them, life is meaningless” </i>
                    - Chinese Proverbs<br><br>

                Tip: Selalu hargai dan jangan anggap remeh hal-hal terdekat yang Anda miliki seperti
                 orang tua, saudara dekat, maupun sahabat-sahabat terdekat Anda. 
                 Tanpa dukungan dan kehadiran mereka hidup Anda mungkin akan menjadi hampa. 
                 Jangan lupa kesuksesan dan kenikmatan hidup hanya bisa tercapai karena dukungan 
                 dari orang-orang di sekitar Anda. 
                Selalu hargai keberadaan mereka dan berilah perhatian selagi masih bisa.
            </p>
        </div>

        <div class="container-fakta-item">
            <p class="judul-fakta">Nikmati dan Hargai Perubahan dalam Kehidupan</p><hr>
            <p>“Perubahan itu menyakitkan, Ia menyebabkan orang merasa tidak aman, bingung, dan marah. 
                Orang menginginkan hal seperti sediakala, karena mereka ingin hidup yang mudah” - Richard Marcinko. <br>
    
                <i>“Change hurts. It makes people insecure, confused, and angry. 
                    People want things to be the same as they’ve always been, because that makes life easier”  </i>
                    - Richard Marcinko.<br><br>

                Tip: Perubahan adalah sesuatu yang memang terkadang menakutkan, membuat kita tidak nyaman,
                    bingung, dan sulit untuk beradaptasi. Akan tetapi perubahan perlu dilakukan bila Anda ingin 
                    berkembang menjadi pribadi yang lebih baik dan tahan banting. 
                    Seringkali perubahan lingkungan menjadi salah satu faktor utama mengapa perubahan terkadang 
                    datang tanpa kita sadari dan kita dituntut untuk menjadi seseorang yang mampu beradaptasi. 
                    Berubahlah sekarang selagi masih sempat, fokuskan perhatian Anda pada hukuman yang akan Anda 
                    terima pada masa mendatang jika tidak mengambil tindakan sekarang.
            </p>
        </div>
    
        <div class="container-fakta-item fakta-even">
            <p class="judul-fakta">Memaafkan Membuat Anda Menjadi Pribadi yang Semakin Kuat</p><hr>
            <p>“Orang yang lemah tidak mampu memaafkan. Memaafkan adalah ciri orang yang kuat” - Mahatma Gandhi<br>
        
                <i>“The weak can never forgive. Forgiveness is the attribute of the strong.”</i>
                    - Mahatma Gandhi.<br><br>

                    Tip: Sikap memaafkan orang-orang yang pernah bersalah pada kita adalah sikap yang dimiliki 
                    oleh orang-orang yang berkarakter kuat. Tindakan memaafkan adalah sebuah tindakan dari seseorang 
                    untuk melupakan kesalah orang lain. Dengan memaafkan, kita telah meringankan pikiran, tenaga, dan 
                    waktu kita. Dendam atau kebencian merupakan hal yang dapat menghambat kemajuan kita dalam hidup. 
                    Jangan diam dan berpikir bahwa waktu akan menyembuhkan hati yang terluka, karena Andalah 
                    satu-satunya yang berhak melupakan dan mengampuni siapapun yang bersalah pada Anda. 
                    Banggalah pada diri Anda bila mampu memaafkan orang lain karena memaafkan adalah tindakan orang kuat.
                </p>
        </div>

        <div class="container-fakta-item">
            <p class="judul-fakta">Perubahan Kecil dapat Memberikan Dampak Besar</p><hr>
            <p>“Kembangkan sikap untuk selalu menjadi lebih baik. 
                Membuat perbedaan yang kecil dalam tindakan akan menghasilkan perbedaan yang besar dalam 
                hasil yang diperoleh” - Brian Tracy<br>
    
                <i>“Develop the winning edge. Small differences in your performance can lead to large
                     differences in your results”</i>
                    - Brian Tracy<br><br>

                Tip: Sekecil apapun perubahan yang Anda lakukan asalkan ke arah yang lebih baik 
                akan membantu hidup Anda menjadi lebih baik. Dengan melakukan perubahan kecil secara
                    rutin dan dengan usaha yang tulus akan membuat sebuah perubahan yang besar pada 
                    kehidupan Anda dibandingkan tidak melakukan perubahan sama sekali. Ingat bahwa 
                    sekecil apapun tindakan yang membuat kehidupan Anda semakin positif akan membawa
                    dampak besar di masa depan.
            </p>
        </div>
        <a href="https://www.cermati.com/artikel/kata-kata-motivasi-hidup-terbaik-untuk-buat-hidup-kamu-lebih-semangat">Sumber: cermati.com (klik untuk menuju ke laman sumber)</a>
    </div>
{% endblock content %}

portofolio/templates/portofolio/portofolio.html
{% extends "portofolio/template.html" %}
{% load static %}
{% block title %} Portofolio {% endblock %}
{% block content %}
    <div class="container-fluid porto-content1">
        <h4>Foto yang saya ambil:</h4>
        <img src="{% static 'images/Foto1.jpg' %}" class="img-fluid porto-foto">
        <img src="{% static 'images/Foto2.jpg' %}" class="img-fluid porto-foto">
        <img src="{% static 'images/Foto3.jpg' %}" class="img-fluid porto-foto">
    </div>
    <div class="container-fluid porto-content2">
        <h4>Desain yang pernah saya buat:</h4>
        <img src="{% static 'images/Desain1.jpg' %}" class="img-fluid porto-foto">
        <img src="{% static 'images/Desain2.jpg' %}" class="img-fluid porto-foto">
    </div>
{% endblock content %}

portofolio/templates/portofolio/riwayat.html
{% extends "portofolio/template.html" %}
{% load static %}
{% block title %} Riwayat Hidup {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="container-riwayat-item">
                    <img src="{% static 'images/College.png' %}" class="logo-riwayat">
                    <p>TK Marsudirini Bekasi (2003 - 2006)</p>
                    <p>SD Marsudirini Bekasi (2006 - 2012)</p>
                    <p>SMP Marsudirini Bekasi (2012 - 2015)</p>
                    <p>SMA Marsudirini Bekasi (2015 - 2018)</p>
                    <p>Universitas Indonesia (2018 - sekarang)</p>
                </div>

                <div class="container-riwayat-item">
                    <img src="{% static 'images/skills.png' %}" class="logo-riwayat">
                    <p>Skills:</p>
                    <p>Fotografi</p>
                    <p>HTML</p>
                    <p>CSS</p>
                    <p>Python</p>
                    <p>Java</p>
                </div>
            </div>
        
            <div class="col-12">
                <div class="container-riwayat-item">
                    <img src="{% static 'images/organization.png' %}" class="logo-riwayat">
                    <hr>
                    <p>BEM FASILKOM UI</p>
                    <p>- Departemen Advokasi dan Kesejahteraan Mahasiswa</p>
                    <hr>
                    <p>COMPFEST 11</p>
                    <p>- Staff of Playground</p>
                    <hr>
                    <p>OSIS SMA MARSUDIRINI BEKASI</p>
                    <p>- Sie. Kehidupan berbangsa dan bernegara (2016)</p>
                    <p>- Bendahara I (2017)</p>
                    <hr>
                    <p>MISDINAR SANTO BARTOLOMEUS</p>
                    <p>- Wakil Ketua</p>
                </div>

                <div class="container-riwayat-item">
                    <img src="{% static 'images/achievement.png' %}" class="logo-riwayat">
                    <p>Juara III Wild games tingkat SMP</p>
                    <p>- lomba tentang ilmu pengetahuan alam yang diselenggarakan oleh SMAN 1 Bekasi</p>
                    <hr>
                    <p>Nilai UN tertinggi SD tingkat sekolah</p>
                </div>
            </div>
            
            <div class="col-12">
                <div class="container-riwayat-item">
                    <img src="{% static 'images/personality.png' %}" class="logo-riwayat">
                    <p>Tipe Kepribadian MBTI: ESFJ - A</p>
                    <hr>
                    <p>Kekuatan: </p>
                    <p>Bertanggung jawab</p>
                    <p>Disiplin</p>
                    <p>Suka membantu</p>
                    <p>Dapat mengemudi</p>
                    <p>Terorganisir</p>
                    <hr>
                    <p>Kelemahan: </p>
                    <p>Terlalu banyak berpikir</p>
                    <p>Penyakit asma dan maag</p>
                    <hr>
                    <p>Kesempatan: </p>
                    <p>Adanya lamaran kerja</p>
                    <p>Dukungan dari orang terdekat</p>
                    <hr>
                    <p>Ancaman: </p>
                    <p>Asma dan Maag yang mungkin saja kambuh</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

portofolio/templates/portofolio/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock %} - Evando's Profile</title>
</head>
<body>
    <header>
        <h1>Evando Wihalim</h1>
    </header>
    
    <div class="navbar">
        <ul>
            {% with url_name=request.resolver_match.url_name %}
            <li><a class="{% if url_name == 'beranda' %} active {% endif %}" href="{% url 'beranda' %}">Beranda</a></li>
            <li><a class="{% if url_name == 'riwayat' %} active {% endif %}" href="{% url 'riwayat' %}">Riwayat Hidup</a></li>
            <li><a class="{% if url_name == 'fakta' %} active {% endif %}" href="{% url 'fakta' %}">Fakta Unik</a></li>
            <li><a class="{% if url_name == 'porto' %} active {% endif %}" href="{% url 'porto' %}">Portofolio</a></li>
            <li><a class="{% if url_name == 'motivasi' %} active {% endif %}" href="{% url 'motivasi' %}">Motivasi</a></li>
            <li><a class="{% if url_name == 'jadwal_form' %} active {% endif %}" href="{% url 'jadwal:jadwal_form' %}">Jadwal</a></li>
            {% endwith %}
        </ul>
    </div>
    {% block content %}{% endblock %}
    <div class="footer">
        <p id="hub">Hubungi saya:</p>
        <div class="logo">
            <a href="https://id-id.facebook.com/evando.wihalim"><img class="logo-item" src="{% static 'images/FB.png' %}"></a>
            <a href="https://www.instagram.com/evando_w/"><img class="logo-item" src="{% static 'images/IG.png' %}"></a>
            <a href="https://id.linkedin.com/in/evando-wihalim-1017a417b"><img class="logo-item" src="{% static 'images/LinkedIN.png' %}"></a>
            <a href="https://wa.me/6287882860328"><img class="logo-item" src="{% static 'images/WA.png' %}"></a>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>